//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntryTime()
        {
            this.EntryTime1 = new HashSet<EntryTime>();
        }
    
        public int Id { get; set; }
        public int ProjectUserCategory_Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public double Hour { get; set; }
        public int Is_Approved { get; set; }
        public int Is_Authorize { get; set; }
        public System.DateTime Created_At { get; set; }
        public Nullable<int> EntryTime_Id { get; set; }
        public string RejectReason { get; set; }
        public string DeleteReason { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntryTime> EntryTime1 { get; set; }
        public virtual EntryTime EntryTime2 { get; set; }
        public virtual ProjectUserCategory ProjectUserCategory { get; set; }
    }
}
