//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectCategory()
        {
            this.ProjectUserCategories = new HashSet<ProjectUserCategory>();
        }
    
        public int Id { get; set; }
        public int Project_Id { get; set; }
        public int Is_Authorize { get; set; }
        public int LaborCategory_Id { get; set; }
        public string Cost { get; set; }
    
        public virtual LaborCategory LaborCategory { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectUserCategory> ProjectUserCategories { get; set; }
    }
}
