//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StartDate
    {
        public int Id { get; set; }
        public System.DateTime StartingDate { get; set; }
        public Nullable<int> IsActive { get; set; }
    }
}
