//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacationBank
    {
        public int Id { get; set; }
        public double VacationHoursPerYear { get; set; }
        public Nullable<double> AccuralVacationHours { get; set; }
        public int PayperiodCount { get; set; }
        public Nullable<int> Is_Authorize { get; set; }
        public int User_Id { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    
        public virtual User User { get; set; }
    }
}
